# Generated by Django 3.0 on 2022-11-18 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test_result',
            name='tester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tester_result', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_test_item',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_test', to='tests.Request_test'),
        ),
        migrations.AddField(
            model_name='request_test',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rtest_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_test',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_test', to='requests.Request'),
        ),
        migrations.AddField(
            model_name='request_test',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rtest_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
