# Generated by Django 3.0 on 2023-07-14 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WOMain',
            fields=[
                ('batch_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('workstation', models.CharField(blank=True, max_length=20, null=True)),
                ('wo_no', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_main_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WODetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfm_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ctr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('step_no', models.CharField(blank=True, max_length=20, null=True)),
                ('step_code', models.CharField(blank=True, max_length=20, null=True)),
                ('step_name', models.CharField(blank=True, max_length=20, null=True)),
                ('wo_qty', models.IntegerField(default=0)),
                ('wo_labor_time', models.IntegerField(default=0)),
                ('wo_mach_time', models.IntegerField(default=0)),
                ('std_qty', models.IntegerField(default=0)),
                ('wo_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wo_main', to='production.WOMain')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelTemp',
            fields=[
                ('batch_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('workstation', models.CharField(blank=True, max_length=20, null=True)),
                ('wo_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cfm_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ctr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('step_no', models.CharField(blank=True, max_length=20, null=True)),
                ('step_code', models.CharField(blank=True, max_length=20, null=True)),
                ('step_name', models.CharField(blank=True, max_length=20, null=True)),
                ('wo_qty', models.IntegerField(default=0)),
                ('wo_labor_time', models.IntegerField(default=0)),
                ('wo_mach_time', models.IntegerField(default=0)),
                ('std_qty', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wo_excel_temp_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
