# Generated by Django 3.0 on 2023-07-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='womain',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
