# Generated by Django 3.0 on 2023-07-17 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0003_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='create_by',
        ),
        migrations.AddField(
            model_name='record',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='update_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_update_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
