# Generated by Django 3.0 on 2023-07-19 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0005_auto_20230718_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(max_length=30)),
                ('record_dt', models.CharField(max_length=10)),
                ('time_code', models.CharField(blank=True, max_length=20, null=True)),
                ('time_name', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('labor_time', models.FloatField(default=0)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='record2_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
