# Generated by Django 3.0 on 2023-07-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_record2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceltemp',
            old_name='workstation',
            new_name='spec',
        ),
        migrations.RemoveField(
            model_name='womain',
            name='workstation',
        ),
        migrations.AddField(
            model_name='exceltemp',
            name='work_center',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='work_center',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wodetail',
            name='work_center',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womain',
            name='spec',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='cfm_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='sap_emp_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='womain',
            name='wo_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
