# Generated by Django 3.0 on 2023-07-21 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0007_auto_20230720_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('type_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='worktype_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
