# Generated by Django 3.0 on 2023-07-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_worktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record2',
            name='time_code',
        ),
        migrations.RemoveField(
            model_name='record2',
            name='time_name',
        ),
        migrations.AddField(
            model_name='record2',
            name='work_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_work_type', to='production.WorkType'),
            preserve_default=False,
        ),
    ]
