# Generated by Django 3.0 on 2023-07-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20230721_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='spec',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(default='Box', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='wo_no',
            field=models.CharField(default='WO', max_length=20),
            preserve_default=False,
        ),
    ]
