# Generated by Django 3.0 on 2023-07-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20230724_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltemp',
            name='plant',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='womain',
            name='plant',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
