# Generated by Django 3.0 on 2023-07-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20230724_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ctr_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
