# Generated by Django 3.0 on 2023-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_record_ctr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sap_flag',
            field=models.BooleanField(default=False),
        ),
    ]
