# Generated by Django 3.0 on 2023-07-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_record_sap_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='plant',
            field=models.CharField(default='302A', max_length=10),
            preserve_default=False,
        ),
    ]
