# Generated by Django 3.0 on 2023-07-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_record_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='record2',
            name='sap_emp_no',
            field=models.CharField(default='30218116', max_length=30),
            preserve_default=False,
        ),
    ]
