# Generated by Django 3.0 on 2023-08-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_record2_sap_emp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='step_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
