# Generated by Django 3.0 on 2023-08-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_record_step_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltemp',
            name='item_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='item_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='womain',
            name='item_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exceltemp',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
