# Generated by Django 3.0 on 2023-08-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_auto_20230801_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='type_name_en',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktype',
            name='type_name_vi',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
