# Generated by Django 3.0 on 2023-08-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20230802_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='item_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
