# Generated by Django 3.0 on 2023-08-17 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0019_auto_20230804_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='COOIS_Record',
            fields=[
                ('batch_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coois_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
