# Generated by Django 3.0 on 2023-08-17 10:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('production', '0020_coois_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='womain',
            old_name='batch_no',
            new_name='id',
        ),
    ]
