# Generated by Django 3.0 on 2023-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_auto_20230817_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='womain',
            name='batch_no',
            field=models.CharField(default=11111, max_length=20),
            preserve_default=False,
        ),
    ]
