# Generated by Django 3.0 on 2023-08-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_womain_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='coois_record',
            name='file_url',
            field=models.CharField(default=11111, max_length=50),
            preserve_default=False,
        ),
    ]
