# Generated by Django 3.0 on 2023-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_coois_record_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
