# Generated by Django 3.0 on 2023-09-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_record_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
