# Generated by Django 3.0 on 2023-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='id',
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach_code',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
