# Generated by Django 3.0 on 2023-11-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_auto_20231107_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='mach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='record_mach', to='production.Machine'),
        ),
    ]
