# Generated by Django 3.2.23 on 2024-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='cfm_code',
            field=models.CharField(default='0001937557', max_length=20),
            preserve_default=False,
        ),
    ]
