# Generated by Django 3.2.23 on 2024-02-27 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0030_consumption_cfm_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sync_SAP_Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=20)),
                ('series_no', models.IntegerField()),
            ],
            options={
                'unique_together': {('function', 'series_no')},
            },
        ),
        migrations.CreateModel(
            name='Sync_SAP_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=20)),
                ('batch_no', models.CharField(max_length=20)),
                ('from_series_no', models.IntegerField()),
                ('to_series_no', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sap_log_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
