# Generated by Django 3.2.23 on 2024-02-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_auto_20240229_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync_sap_series',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sync_sap_series',
            name='update_by',
            field=models.CharField(default='10.96.101.11', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sync_sap_log',
            name='create_by',
            field=models.CharField(max_length=20),
        ),
    ]
