# Generated by Django 3.2.23 on 2024-03-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_auto_20240229_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('function', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('series', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='consumption',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record2',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
