# Generated by Django 3.2.23 on 2024-03-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_record2_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='function',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('function', 'key')},
        ),
    ]
