# Generated by Django 3.2.23 on 2024-03-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0038_auto_20240325_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sync_SAP_Series',
        ),
    ]
