# Generated by Django 3.2.23 on 2024-03-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_auto_20240326_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync_sap_log',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
