# Generated by Django 3.2.23 on 2024-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_sync_sap_log_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='wo_mtrl_no',
            field=models.CharField(default='0010', max_length=20),
            preserve_default=False,
        ),
    ]
