# Generated by Django 3.0 on 2022-12-16 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0005_assetarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='category_no',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='category_no',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='assetarea',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brand_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='label_attachment',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='label_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(max_length=1000)),
                ('owner_unit', models.CharField(max_length=50)),
                ('keeper_unit', models.CharField(max_length=50)),
                ('keeper_no', models.CharField(max_length=50)),
                ('keeper_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pur_date', models.CharField(blank=True, max_length=50, null=True)),
                ('pur_price', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_area', to='assets.AssetArea')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_brand', to='assets.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_category', to='assets.AssetCategory')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_create_by', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_type', to='assets.AssetType')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
