# Generated by Django 3.0 on 2022-12-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20221216_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
