# Generated by Django 3.0 on 2022-12-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20221219_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='auto_encode',
            field=models.BooleanField(default=True),
        ),
    ]
