# Generated by Django 3.0 on 2022-12-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20221221_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
