# Generated by Django 3.0 on 2022-12-21 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_auto_20221221_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_status', to='assets.AssetStatus'),
        ),
    ]
