# Generated by Django 3.0 on 2022-12-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20221221_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_status', to='assets.AssetStatus'),
            preserve_default=False,
        ),
    ]
