# Generated by Django 3.0 on 2022-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20221221_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
    ]
