# Generated by Django 3.0 on 2022-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_auto_20221221_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AddField(
            model_name='series',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
