# Generated by Django 3.0 on 2022-12-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_auto_20221223_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='scrap_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='scrap_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
