# Generated by Django 3.0 on 2023-01-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_auto_20230103_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
