# Generated by Django 3.0 on 2023-04-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_asset_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
