# Generated by Django 3.0 on 2023-06-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_auto_20230523_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sap_asset_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
