# Generated by Django 3.0 on 2023-08-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('assets', '0026_asset_sap_asset_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='perm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_group', to='auth.Group'),
        ),
    ]
