# Generated by Django 3.0 on 2023-11-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0028_asset_label_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('before', models.CharField(blank=True, max_length=20, null=True)),
                ('after', models.CharField(blank=True, max_length=20, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hist_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
