# Generated by Django 3.0 on 2023-11-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='asset',
            field=models.ForeignKey(default='1000176', on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_history', to='assets.Asset'),
            preserve_default=False,
        ),
    ]
