# Generated by Django 3.2.23 on 2023-12-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_history_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_history', to='assets.asset'),
        ),
    ]
