# Generated by Django 3.0 on 2023-07-03 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20230703_1118'),
        ('inventory', '0002_auto_20230703_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_status_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('received_qty', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_item', to='inventory.ItemCategory')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.CharField(default='2023-07-03', max_length=10)),
                ('ext_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=2000, null=True)),
                ('total', models.IntegerField(default=0)),
                ('admin_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_status', to='inventory.FormStatus')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_unit', to='users.Unit')),
            ],
        ),
    ]
