# Generated by Django 3.0 on 2023-07-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_appliedform_applieditem_formstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieditem',
            name='applied_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applied_form_item', to='inventory.AppliedForm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedform',
            name='reason',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='原因'),
        ),
    ]
