# Generated by Django 3.0 on 2023-07-05 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20230705_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedform',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliedform',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inv_form_create_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
