# Generated by Django 3.0 on 2023-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20230706_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
