# Generated by Django 3.0 on 2023-07-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
