# Generated by Django 3.0 on 2023-07-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieditem',
            name='unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
