# Generated by Django 3.0 on 2023-07-07 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_applieditem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedform',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_form_approver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedform',
            name='apply_date',
            field=models.CharField(default='2023-07-07', max_length=10),
        ),
        migrations.AlterField(
            model_name='appliedform',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_form_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
