# Generated by Django 3.0 on 2023-07-07 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0011_auto_20230707_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedform',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_form_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
