# Generated by Django 3.0 on 2023-07-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20230707_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applieditem',
            name='item',
        ),
        migrations.AddField(
            model_name='applieditem',
            name='item_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applieditem',
            name='spec',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
