# Generated by Django 3.0 on 2023-07-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20230719_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedform',
            name='apply_date',
            field=models.CharField(default='2023-07-20', max_length=10),
        ),
    ]
