# Generated by Django 3.0 on 2023-08-08 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0024_auto_20230804_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedform',
            name='apply_date',
            field=models.CharField(default='2023-08-08', max_length=10),
        ),
        migrations.CreateModel(
            name='Apply_attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploads/inventory/apply/')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_files', to='inventory.AppliedForm')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_files_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
