# Generated by Django 3.0 on 2023-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20230808_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_attachment',
            name='files',
            field=models.FileField(upload_to='uploads/inventory/apply/%Y/%m/'),
        ),
    ]
