# Generated by Django 3.0 on 2023-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20230808_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieditem',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliedform',
            name='apply_date',
            field=models.CharField(default='2023-08-10', max_length=10),
        ),
    ]
