# Generated by Django 3.0 on 2023-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20230810_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedform',
            name='form_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
