# Generated by Django 3.0 on 2023-08-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0028_auto_20230810_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedform',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedform',
            name='update_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inv_form_update_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
