# Generated by Django 3.0 on 2023-08-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20230817_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='applieditem',
            name='category',
            field=models.CharField(default='文具用品', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliedform',
            name='apply_date',
            field=models.CharField(default='2023-08-18', max_length=10),
        ),
    ]
