# Generated by Django 3.0 on 2023-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20230818_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieditem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
