# Generated by Django 3.0 on 2023-09-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_auto_20230829_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedform',
            name='approve_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appliedform',
            name='apply_date',
            field=models.CharField(default='2023-09-05', max_length=10),
        ),
    ]
