# Generated by Django 3.2.23 on 2024-03-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_rename_asset_pic_attachment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=50)),
                ('values', models.CharField(max_length=500)),
            ],
        ),
    ]
