# Generated by Django 3.2.23 on 2024-03-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20240313_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='family',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='item_family_category', to='inventory.itemfamily'),
            preserve_default=False,
        ),
    ]
