# Generated by Django 3.2.23 on 2024-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_auto_20240313_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applieditem',
            name='item_code',
            field=models.CharField(max_length=11),
        ),
    ]
