# Generated by Django 3.2.23 on 2024-03-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0047_alter_applieditem_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfamily',
            name='perm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_group', to='auth.group'),
        ),
    ]
