# Generated by Django 3.2.23 on 2024-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_itemfamily_perm_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
