# Generated by Django 3.2.23 on 2024-03-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_item_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='is_stock',
        ),
    ]
