# Generated by Django 3.2.23 on 2024-04-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_item_safe_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='safe_qty',
        ),
    ]
