# Generated by Django 3.2.23 on 2024-05-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0052_remove_item_safe_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_file', models.FileField(upload_to='static/inventory/')),
                ('stamp_file', models.FileField(upload_to='static/inventory/')),
                ('print_file', models.FileField(upload_to='static/inventory/')),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='template_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
