# Generated by Django 3.2.23 on 2024-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_template_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_attachment',
            name='key_file',
            field=models.FileField(upload_to='inventory/template/'),
        ),
        migrations.AlterField(
            model_name='template_attachment',
            name='print_file',
            field=models.FileField(upload_to='inventory/template/'),
        ),
        migrations.AlterField(
            model_name='template_attachment',
            name='stamp_file',
            field=models.FileField(upload_to='inventory/template/'),
        ),
    ]
