# Generated by Django 3.0 on 2023-06-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_auto_20221118_2345'),
        ('problems', '0004_auto_20230210_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_status',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='problem_status', to='bases.Status'),
            preserve_default=False,
        ),
    ]
