# Generated by Django 3.2.25 on 2024-08-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20240806_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='issue_owner',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='record_date',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_datetime',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Problem Datetime'),
        ),
    ]
