# Generated by Django 3.2.25 on 2024-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='publisher',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Publisher Worker'),
        ),
    ]
