# Generated by Django 3.2.25 on 2024-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='issue_owner',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='publisher',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Issue Owner'),
        ),
    ]
