# Generated by Django 3.2.25 on 2024-08-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20240806_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='record_date',
            field=models.TimeField(blank=True, max_length=20, null=True, verbose_name='Record Date'),
        ),
    ]
