# Generated by Django 3.2.25 on 2024-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problem_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='record_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Record Date'),
        ),
    ]
