# Generated by Django 3.0 on 2023-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='command',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
