# Generated by Django 3.0 on 2023-05-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(max_length=50, unique=True)),
                ('app_dept', models.CharField(max_length=50, unique=True)),
                ('app_user', models.CharField(max_length=50, unique=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('apply_date', models.CharField(blank=True, max_length=10, null=True)),
                ('expect_date', models.CharField(blank=True, max_length=10, null=True)),
                ('lend_date', models.CharField(blank=True, max_length=10, null=True)),
                ('return_date', models.CharField(blank=True, max_length=10, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_create_by', to=settings.AUTH_USER_MODEL)),
                ('lend_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lend_owner', to=settings.AUTH_USER_MODEL)),
                ('return_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_owner', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_asset', to='borrow.Borrow')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_item', to='borrow.Borrow')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_item_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
