# Generated by Django 3.0 on 2023-05-04 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_auto_20230407_0918'),
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPMDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_no', models.CharField(max_length=50, unique=True)),
                ('dept_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BPMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.CharField(max_length=50, unique=True)),
                ('user_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='id',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='app_dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='app_user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='form_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_asset', to='assets.Asset'),
        ),
    ]
