# Generated by Django 3.0 on 2023-05-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20230504_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='borrowitem',
            name='qty',
        ),
    ]
