# Generated by Django 3.0 on 2023-05-04 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0003_auto_20230504_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='create_by',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
