# Generated by Django 3.0 on 2023-05-04 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0004_auto_20230504_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='lend_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lend_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
