# Generated by Django 3.0 on 2023-05-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_auto_20230504_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowitem',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='borrowitem',
            name='create_by',
        ),
    ]
