# Generated by Django 3.0 on 2023-06-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0008_borrow_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default='2023-06-12', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default='2023-06-12', max_length=10),
        ),
    ]
