# Generated by Django 3.0 on 2023-06-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0010_auto_20230616_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default='2023-06-28', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default='2023-06-28', max_length=10),
        ),
    ]
