# Generated by Django 3.0 on 2023-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0012_auto_20230630_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default='2023-07-03', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default='2023-07-03', max_length=10),
        ),
    ]
