# Generated by Django 3.0 on 2023-07-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0015_auto_20230706_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default='2023-07-07', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default='2023-07-07', max_length=10),
        ),
    ]
