# Generated by Django 3.0 on 2023-07-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0023_auto_20230724_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default='2023-07-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default='2023-07-25', max_length=10),
        ),
    ]
