# Generated by Django 3.0 on 2023-09-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0036_auto_20230905_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='apply_date',
            field=models.CharField(default='2023-09-11', max_length=10),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='expect_date',
            field=models.CharField(default='2023-09-11', max_length=10),
        ),
    ]
