# Generated by Django 3.2.23 on 2024-03-14 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='storage_location', to='stock.storage')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location_bin', to='stock.location')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bin_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
