# Generated by Django 3.2.23 on 2024-03-21 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_movementtype_stock_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInForm',
            fields=[
                ('form_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apply_date', models.CharField(max_length=10)),
                ('pr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_form_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
