# Generated by Django 3.2.23 on 2024-03-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_stockinform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinform',
            name='pr_no',
        ),
        migrations.AlterField(
            model_name='stockinform',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_form_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockinform',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_form_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
