# Generated by Django 3.2.23 on 2024-03-22 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_auto_20240322_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinform',
            name='pr_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockinform',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_form_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockinform',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockin_form_requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockOutForm',
            fields=[
                ('form_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apply_date', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_form_create_by', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_form_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
