# Generated by Django 3.0 on 2023-05-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='emp_no',
            field=models.CharField(default='', max_length=30, verbose_name='工號'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_type', to='users.UserType'),
        ),
    ]
