# Generated by Django 3.0 on 2023-06-30 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230516_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='update_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_type_update_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitId', models.CharField(max_length=30, unique=True, verbose_name='部門編號')),
                ('orgId', models.CharField(max_length=30, verbose_name='組織編號')),
                ('unitName', models.CharField(max_length=30, verbose_name='部門名稱')),
                ('isValid', models.CharField(default=0, max_length=1, verbose_name='失效')),
                ('cost_center', models.CharField(blank=True, max_length=30, null=True, verbose_name='成本中心')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
