# Generated by Django 3.0 on 2023-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230630_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emp_no',
            field=models.CharField(max_length=30, unique=True, verbose_name='工號'),
        ),
    ]
