# Generated by Django 3.0 on 2023-07-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230706_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sap_emp_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SAP工號'),
        ),
    ]
