# Generated by Django 3.0 on 2023-08-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_sap_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emp_no',
            field=models.CharField(max_length=30, unique=True, verbose_name='emp_no'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sap_emp_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='sap_emp_no'),
        ),
    ]
