# Generated by Django 3.0 on 2022-11-18 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        ('projects', '0002_auto_20221118_2345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0002_auto_20221118_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_create_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_level', to='requests.Level'),
        ),
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_project', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_level', to='bases.Status'),
        ),
        migrations.AddField(
            model_name='request',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_update_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_create_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='level',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='level_update_at', to=settings.AUTH_USER_MODEL),
        ),
    ]
